#! /bin/sh -e

$(which git) submodule update --init --recursive

VERSION=nixpkgs-unstable

SYSTEM=$(nix-instantiate --eval --expr "builtins.currentSystem")
exec nix-shell dev-env.nix -I nixpkgs=https://github.com/thpham/nixpkgs/archive/$VERSION.tar.gz --exclude tarball "$@"