apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://{kube-apiserver-hostname}
  name: nixops-k8s
contexts:
- context:
    cluster: nixops-k8s
    user: nixops-admin
  name: nixops-k8s
- context:
    cluster: nixops-k8s
    user: nixops-admin-oidc
  name: nixops-k8s-oidc
current-context: nixops-k8s
kind: Config
preferences: {}
users:
- name: nixops-admin
  user:
    as-user-extra: {}
    password: kubernetes
    username: adminn
  user:
    as-user-extra: {}
    password: kubernetes
    username: admin
- name: nixops-admin-oidc
  user:
    auth-provider:
      name: oidc
      config:
        idp-issuer-url: https://{your_idP_domain}/auth/realms/master
        client-id: kubernetes
        client-secret: YOUR_SECRET
        id-token: ey...       # try kubelogin to update this!
        refresh-token: ey...  # idem
